### ISSUE TITLE
Error: Cannot find module 'postcss-preset-mantine' with nextjs app dir build on cloudflare pages

### ISSUE THREAD

**Issue by resdevd** [mantinedev/postcss-preset-mantine#5]
We have followed the guide at https://github.com/mantinedev/next-app-template

This error doesn't occur in our local machines but fails repeatedly in cloulflare pages build deployment. 

We've tried node v17 and node v18 in the cloudflare environment. This error doesn't occur in our local envrionments, this issue may not is even in this package, but curious if anyone has a pointer to some additional setting. 

```
01:56:58.048	./styles/home.module.css
01:56:58.048	Error: Cannot find module 'postcss-preset-mantine'
01:56:58.048	Require stack:
01:56:58.048	- /opt/buildhome/repo/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
01:56:58.048	- /opt/buildhome/repo/node_modules/next/dist/build/webpack/config/blocks/css/index.js
01:56:58.048	- /opt/buildhome/repo/node_modules/next/dist/build/webpack/config/index.js
01:56:58.049	- /opt/buildhome/repo/node_modules/next/dist/build/webpack-config.js
01:56:58.049	- /opt/buildhome/repo/node_modules/next/dist/build/webpack-build/impl.js
01:56:58.049	- /opt/buildhome/repo/node_modules/next/dist/build/webpack-build/index.js
01:56:58.049	- /opt/buildhome/repo/node_modules/next/dist/build/index.js
01:56:58.049	- /opt/buildhome/repo/node_modules/next/dist/cli/next-build.js
01:56:58.049	- /opt/buildhome/repo/node_modules/next/dist/lib/commands.js
01:56:58.049	- /opt/buildhome/repo/node_modules/next/dist/bin/next
01:56:58.049	    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
01:56:58.049	    at /opt/buildhome/repo/node_modules/next/dist/server/require-hook.js:110:36
01:56:58.050	    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
01:56:58.050	    at loadPlugin (/opt/buildhome/repo/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:54:32)
01:56:58.050	    at /opt/buildhome/repo/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:162:56
01:56:58.050	    at Array.map (<anonymous>)
01:56:58.050	    at getPostCssPlugins (/opt/buildhome/repo/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:162:47)
01:56:58.051	    at async /opt/buildhome/repo/node_modules/next/dist/build/webpack/config/blocks/css/index.js:124:36
01:56:58.051	
01:56:58.051	Import trace for requested module:
01:56:58.051	./styles/home.module.css
01:56:58.051	./app/page.js
01:56:58.051	
01:56:58.051	
01:56:58.051	> Build failed because of webpack errors
01:56:58.157	Failed: build command exited with code: 1
01:56:59.052	Failed: error occurred while running build command
```

**Comment by resdevd** [comment]
Fixed it by moving postcss devDependencies to main dependencies, as it looks like there's something going on with production flag variable in edge platforms. Not sure if it impacts performance but the blocker has been cleared. 

Thanks for the amazing work with v7 with nextjs app router compatibility bdw.
